//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.GCWS;

[assembly: RegisterDocumentType(NewsSection.CLASS_NAME, typeof(NewsSection))]

namespace CMS.DocumentEngine.Types.GCWS
{
	/// <summary>
	/// Represents a content item of type NewsSection.
	/// </summary>
	public partial class NewsSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "GCWS.NewsSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with NewsSection fields.
		/// </summary>
		private readonly NewsSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with NewsSection fields.
		/// </summary>
		[RegisterProperty]
		public NewsSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with NewsSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class NewsSectionFields : AbstractHierarchicalObject<NewsSectionFields>
		{
			/// <summary>
			/// The content item of type NewsSection that is a target of the extended API.
			/// </summary>
			private readonly NewsSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="NewsSectionFields" /> class with the specified content item of type NewsSection.
			/// </summary>
			/// <param name="instance">The content item of type NewsSection that is a target of the extended API.</param>
			public NewsSectionFields(NewsSection instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="NewsSection" /> class.
		/// </summary>
		public NewsSection() : base(CLASS_NAME)
		{
			mFields = new NewsSectionFields(this);
		}

		#endregion
	}
}